#!/bin/bash
if [ "$#" -ne 1 ]; then
  echo "usage: split_prep_file <prep-file-name>"
  exit
fi

if [ ! -f "$1" ]; then
    echo "error: file '$1' was not found"
    exit
fi

csplit $1 '/.*INT\ 0$/' '{*}'
for OUTPUT in $(ls xx*)
do
  NAME=$(head -n 1 $OUTPUT | cut -d ' ' -f 1)
  mv $OUTPUT $NAME.prep
done

